### PR TITLE
Can we have a release 0.1.5 on pypi?

### PR DESCRIPTION
**Pull request by msom**

### CODE REVIEW

**Comment by maximumG** [comment]
@msom I can provide you the right to push to the PyPi repository. Just give me your username of the platform. 

Unfortunately I cannot maintain the library anymore as I'm not working with Cisco Prime Infrastructure.

**Comment by msom** [comment]
The username is `inshsr`.

If you like, you can also transfer the project to us (https://github.com/HSRNetwork) - we are a Swiss University and probably able to maintain the library for a long time...

**Comment by maximumG** [comment]
I set you as owner of the repository on PyPi. Unfortunatly I cannot transfer the project because you already have a fork of mine (github forbid that). I guess if you delete your fork I would be able to transfer it.

**Comment by msom** [comment]
Ok, I deleted the fork!

**Comment by maximumG** [comment]
Thanks, but still not able to transfer the project. Now Gihub is saying that I cannot create public repository on HSRNetwork. I added @msom as a project collaborator. Could you try to transfer it on your own (_Settings > Options > Danger Zone_).

If you still can't I guess I would need rights to create public repository on HSRNetwork temporarily.

**Comment by msom** [comment]
Seems like I don't have the rights for the settings page. An alternative option would be to transfer the repo to my user account [("You can transfer your repository to any user account that accepts your repository transfer.")](https://help.github.com/en/github/administering-a-repository/transferring-a-repository) and then I transfer it to the organization?

**Comment by maximumG** [comment]
I just transfered the repository to your own namespace @msom. Hope the library could live on your side 😃

**Comment by msom** [comment]
Great! I was able to transfer it further. Thanks!

**Pull request closed without merging**
